### ISSUE TITLE
allow defining custom connectionParams for websocket connection

### ISSUE THREAD

**Issue by praveenweb** [Akryum/vue-cli-plugin-apollo#134] opened 2019-04-09 04:35 UTC
Currently the connectionParams in subscriptionClient always returns either of `authorization` or an empty object depending on the availability of the token. [Source here](https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/graphql-client/src/index.js#L112)

This convention doesn't work with [Hasura GraphQL Engine](https://github.com/hasura/graphql-engine) as Hasura expects a `header` object to be returned in connectionParams with authorization key inside the object.

So this is what works with Hasura:

```
wsClient = new SubscriptionClient(wsEndpoint, {
  reconnect: true,
  connectionParams: () => {
    const authorization = getAuth(tokenName)
    return authorization ? { headers: { authorization } } : {}
  },
})
```

Note the authorization object wrapped in a top level headers key.

I think it's better not to assume any convention in the way connectionParams is handled, since different servers will have different ways to handle this.

I would like the plugin to allow the user to define their custom method for `connectionParams`, similar to `getAuth`.

**Comment by thetre97** [comment] 2019-05-02 12:25
Related to https://github.com/Akryum/vue-apollo/issues/520

**Comment by gitxav** [comment] 2019-07-23 21:01
Related to https://github.com/Akryum/vue-cli-plugin-apollo/issues/187

**Comment by Akryum** [comment] 2019-10-20 14:35
Duplicate of the vue-cli-plugin-apollo issue.

**Closed by Akryum** 2019-10-20 14:35 UTC

**Comment by drewbaker** [comment] 2020-04-22 18:04
@Akryum Which issue is this a duplicate of? I really need connectionParams on websockets, so I want to follow the progress of the underlying issue.
